// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuppliesManagement.DBContext;

#nullable disable

namespace SuppliesManagement.Migrations
{
    [DbContext(typeof(SuppliesManagementDBContext))]
    partial class SuppliesManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuppliesManagement.Models.Account", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SuppliesManagement.Models.DonViTinh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DonViTinhs");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HangHoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGiaSauThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGiaTruocThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonViTinhID")
                        .HasColumnType("int");

                    b.Property<Guid?>("HoaDonNhapID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoHangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NhomHangID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongConLai")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDaXuat")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongGiaSauThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongGiaTruocThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VAT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhID");

                    b.HasIndex("HoaDonNhapID");

                    b.HasIndex("KhoHangID");

                    b.HasIndex("NhomHangID");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HangHoaHoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGiaSauThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGiaTruocThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonViTinhID")
                        .HasColumnType("int");

                    b.Property<Guid?>("HoaDonNhapID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoHangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NhomHangID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongGiaSauThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongGiaTruocThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VAT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhID");

                    b.HasIndex("HoaDonNhapID");

                    b.HasIndex("KhoHangID");

                    b.HasIndex("NhomHangID");

                    b.ToTable("HangHoaHoaDons");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HoaDonNhap", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoHangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("KhoHangID");

                    b.ToTable("HoaDonNhaps");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HoaDonXuat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoHangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDoXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("KhoHangID");

                    b.ToTable("HoaDonXuats");
                });

            modelBuilder.Entity("SuppliesManagement.Models.KhoHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhoHangs");
                });

            modelBuilder.Entity("SuppliesManagement.Models.NhapKho", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HangHoaHoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HangHoaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonNhapID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("HangHoaHoaDonId");

                    b.HasIndex("HoaDonNhapID");

                    b.ToTable("NhapKhos");
                });

            modelBuilder.Entity("SuppliesManagement.Models.NhomHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhomHangs");
                });

            modelBuilder.Entity("SuppliesManagement.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SuppliesManagement.Models.XuatKho", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HangHoaHoaDonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonXuatID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("HangHoaHoaDonID");

                    b.HasIndex("HoaDonXuatID");

                    b.ToTable("XuatKhos");
                });

            modelBuilder.Entity("SuppliesManagement.Models.Account", b =>
                {
                    b.HasOne("SuppliesManagement.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HangHoa", b =>
                {
                    b.HasOne("SuppliesManagement.Models.DonViTinh", "DonViTinh")
                        .WithMany("HangHoas")
                        .HasForeignKey("DonViTinhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuppliesManagement.Models.HoaDonNhap", null)
                        .WithMany("HangHoas")
                        .HasForeignKey("HoaDonNhapID");

                    b.HasOne("SuppliesManagement.Models.KhoHang", "KhoHang")
                        .WithMany("HangHoas")
                        .HasForeignKey("KhoHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuppliesManagement.Models.NhomHang", "NhomHang")
                        .WithMany("HangHoas")
                        .HasForeignKey("NhomHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("KhoHang");

                    b.Navigation("NhomHang");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HangHoaHoaDon", b =>
                {
                    b.HasOne("SuppliesManagement.Models.DonViTinh", "DonViTinh")
                        .WithMany("HangHoaHoaDons")
                        .HasForeignKey("DonViTinhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuppliesManagement.Models.HoaDonNhap", null)
                        .WithMany("HangHoaHoaDons")
                        .HasForeignKey("HoaDonNhapID");

                    b.HasOne("SuppliesManagement.Models.KhoHang", "KhoHang")
                        .WithMany("HangHoaHoaDons")
                        .HasForeignKey("KhoHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuppliesManagement.Models.NhomHang", "NhomHang")
                        .WithMany("HangHoaHoaDons")
                        .HasForeignKey("NhomHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("KhoHang");

                    b.Navigation("NhomHang");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HoaDonNhap", b =>
                {
                    b.HasOne("SuppliesManagement.Models.KhoHang", "KhoHang")
                        .WithMany()
                        .HasForeignKey("KhoHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoHang");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HoaDonXuat", b =>
                {
                    b.HasOne("SuppliesManagement.Models.KhoHang", "KhoHang")
                        .WithMany()
                        .HasForeignKey("KhoHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoHang");
                });

            modelBuilder.Entity("SuppliesManagement.Models.NhapKho", b =>
                {
                    b.HasOne("SuppliesManagement.Models.HangHoaHoaDon", "HangHoaHoaDon")
                        .WithMany()
                        .HasForeignKey("HangHoaHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuppliesManagement.Models.HoaDonNhap", "HoaDonNhap")
                        .WithMany()
                        .HasForeignKey("HoaDonNhapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoaHoaDon");

                    b.Navigation("HoaDonNhap");
                });

            modelBuilder.Entity("SuppliesManagement.Models.XuatKho", b =>
                {
                    b.HasOne("SuppliesManagement.Models.HangHoaHoaDon", "HangHoaHoaDon")
                        .WithMany()
                        .HasForeignKey("HangHoaHoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuppliesManagement.Models.HoaDonXuat", "HoaDonXuat")
                        .WithMany()
                        .HasForeignKey("HoaDonXuatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoaHoaDon");

                    b.Navigation("HoaDonXuat");
                });

            modelBuilder.Entity("SuppliesManagement.Models.DonViTinh", b =>
                {
                    b.Navigation("HangHoaHoaDons");

                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("SuppliesManagement.Models.HoaDonNhap", b =>
                {
                    b.Navigation("HangHoaHoaDons");

                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("SuppliesManagement.Models.KhoHang", b =>
                {
                    b.Navigation("HangHoaHoaDons");

                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("SuppliesManagement.Models.NhomHang", b =>
                {
                    b.Navigation("HangHoaHoaDons");

                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("SuppliesManagement.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
